### PR TITLE
add Selector#where(C)

### PR DESCRIPTION
**Pull request by k-kagurazaka**
I added `Selector#conditionGroup()` to build complex condition like:

```java
db.selectFromBook()
        .conditionGroup(it -> it.titleEq("Hoge").or().titleEq("Huga"))
        .and()
        .publisherEq(publisher)
        .toList();
```

The result SQL is `SELECT * FROM Book WHERE (title = "Hoge" OR title = "Huga") AND publisherId = 1`.

### CODE REVIEW

**Comment by gfx** [comment]
Looks good, but why not `where(C conditionGroup)`?

IMO **both** `where(Function<C, C> conditionGroupFunction)` and `where(C conditiongGroup)` are useful.

**Comment by gfx** [comment]
(memo: I'll release a new version soon after this PR is merged)

**Comment by k-kagurazaka** [comment]
I agree with you.
I'll try it.

**Comment by k-kagurazaka** [comment]
I renamed `conditionGroup` to `where` and add tests 👍

**Comment by gfx** [comment]
LGTM

**Pull request merged**
